import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

const mtnBrighterSans = localFont({
  src: [
    { path: "../public/fonts/MTNBrighterSans-ExtraLight.ttf",      weight: "200", style: "normal" },
    { path: "../public/fonts/MTNBrighterSans-ExtraLightItalic.ttf", weight: "200", style: "italic" },
    { path: "../public/fonts/MTNBrighterSans-Light.ttf",            weight: "300", style: "normal" },
    { path: "../public/fonts/MTNBrighterSans-LightItalic.ttf",      weight: "300", style: "italic" },
    { path: "../public/fonts/MTNBrighterSans-Regular.ttf",          weight: "400", style: "normal" },
    { path: "../public/fonts/MTNBrighterSans-RegularItalic.ttf",    weight: "400", style: "italic" },
    { path: "../public/fonts/MTNBrighterSans-Medium.ttf",           weight: "500", style: "normal" },
    { path: "../public/fonts/MTNBrighterSans-MediumItalic.ttf",     weight: "500", style: "italic" },
    { path: "../public/fonts/MTNBrighterSans-Bold.ttf",             weight: "700", style: "normal" },
    { path: "../public/fonts/MTNBrighterSans-BoldItalic.ttf",       weight: "700", style: "italic" },
    { path: "../public/fonts/MTNBrighterSans-ExtraBold.ttf",        weight: "800", style: "normal" },
    { path: "../public/fonts/MTNBrighterSans-ExtraBoldItalic.ttf",  weight: "800", style: "italic" },
  ],
  variable: "--font-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MTN - Vibe Raanaa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mtnBrighterSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <NextTopLoader
          color="var(--color-primary)"
          height={2}
          showSpinner={false}
          shadow={false}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
